### ISSUE TITLE
Suggestion: Add Top 25 output as CLI argument

### ISSUE THREAD

**Issue by minimaxir** [salesforce/ctrl#1]
https://github.com/salesforce/ctrl/blob/master/generation.py#L255

It might be easier to do a CLI arg than uncommenting (perhaps a `--top_n` parameter where the user can supply length)

Adding probabilities for each output (like the Australia charts in the paper) would be fun as well.

**Comment by keskarnitish** [comment]
Fixed in https://github.com/salesforce/ctrl/commit/e38febf468ce223b87628e388d23179d265add17
