### ISSUE TITLE
TPUEstimator uses CPU during generation

### ISSUE THREAD

**Issue by sergeman** [salesforce/ctrl#11]
I am running a patched code on Ubuntu Docker with NVIDIA GPU support on an AMD Threadripper box with a Titan Xp card. The code does not engage GPU and entire inference runs on a CPU. The generation does work, but it is slow. What should I do to engage the GPU?

**Comment by keskarnitish** [comment]
I'd love some more details here. 
Did you use `tensorflow-gpu==1.14`? Are you able to run other CUDA-compatible codes in your environment? Can you paste your Dockerfile?

**Comment by keskarnitish** [comment]
Seems like the problem was solved; reopen if not.
