### ISSUE TITLE
TypeError when running generation.py

### ISSUE THREAD

**Issue by Celeste-cj** [salesforce/ctrl#12]
TypeError: in converted code:

    ctrl/transformer.py:138 call *
        x = getattr(self, "layer%i" % i)(x, training, mask)
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:629 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    ctrl/transformer.py:92 call *
        attn_output  = self.multi_head_attention(normed, normed, normed, mask)
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:629 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    ctrl/transformer.py:60 call *
        q = self.split_into_heads(q, batch_size)
    ctrl/transformer.py:50 split_into_heads
        x = tf.reshape(x, (batch_size, -1, self.num_heads, self.depth))
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py:7715 reshape
        "Reshape", tensor=tensor, shape=shape, name=name)
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:530 _apply_op_helper
        raise err
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:527 _apply_op_helper
        preferred_dtype=default_dtype)
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1224 internal_convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1145 _autopacking_conversion_function
        return _autopacking_helper(v, dtype, name or "packed")
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1094 _autopacking_helper
        constant_op.constant(elem, dtype=dtype, name=str(i)))
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:246 constant
        allow_broadcast=True)
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:284 _constant_impl
        allow_broadcast=allow_broadcast))
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py:466 make_tensor_proto
        _AssertCompatible(values, dtype)
    anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py:371 _AssertCompatible
        (dtype.name, repr(mismatch), type(mismatch).__name__))

    TypeError: Expected int32, got 80.0 of type 'float' instead.

And I found it's the following code that cause the error
`
x = tf.reshape(x, (batch_size, -1, self.num_heads, self.depth))     # transformer.py  line 49
`
`self.depth` should be an integer so that it can be fed into `tf.reshape`

It can be fixed by changing this line
`
self.depth = d_model_size // self.num_heads     # transformer.py  line 40
`

**Comment by keskarnitish** [comment]
Seems like you are using Python3. I just merged https://github.com/salesforce/ctrl/pull/6 which should fix this and other related issues. Can you try pulling the latest version of the code and trying again? 

Closing this for now, reopen if issue persists.
