### ISSUE TITLE
Allow generation to terminate once "finished"

### ISSUE THREAD

**Issue by minimaxir** [salesforce/ctrl#13]
When a generation is "finished" (common with Reddit control codes) before the specified generation length, the model just outputs newlines forever. There should be a way to detect this behavior and stop generations.

**Comment by keskarnitish** [comment]
I've deliberately made it continue generating by disallowing the `Score` token (which marks the end of a Reddit data point); see https://github.com/salesforce/ctrl/blob/master/generation.py#L212. 

You could use the same check to stop generation if you want a finished prompt. 
It's harder to detect for things like Wikipedia or News though. We are hoping to address this in our next large training run. 

Closing for now, reopen as necessary.
