### ISSUE TITLE
NameError: global name 'tf' is not defined

### ISSUE THREAD

**Issue by calculusoflambdas** [salesforce/ctrl#15]
What am I doing wrong?
This is the rough Dockerfile which I expected to work, but throws the above error:

`FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04`
`RUN apt-get update && apt-get install -y git curl wget python python-pip vim`
`RUN pip install Cython`
`RUN pip install numpy tensorflow-gpu==1.14`
`RUN mkdir /CTRL`
`WORKDIR /CTRL`
`RUN git clone https://github.com/salesforce/ctrl.git .`
`RUN git clone https://github.com/glample/fastBPE.git`
`RUN cd fastBPE && g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast && \
    python setup.py install`
`RUN patch -b /usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py estimator.patch`
`RUN mkdir model1`

On the host I get the models to save doing it in the dockerfile as I'm experimenting :
 `wget https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/checkpoint && \
  wget https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/model.ckpt-413000.data-00000-of-00001 && \
  wget https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/model.ckpt-413000.index && \
  wget https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/model.ckpt-413000.meta `

And then mount that into the docker image (for experimenting):
`nvidia-docker run -it --rm -v $(pwd)/../model256:/CTRL/model1 calculusoflabmdas/ctrl:v4 bash`

Running: 
`python generation.py --model_dir model1/ `
gives the usual list of warnings before failing out with:

```
Model: "model"

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 256)]        0                                            
__________________________________________________________________________________________________
tied_embedding_softmax (TiedEmb multiple             315810054   input_1[0][0]                    
                                                                 encoder[0][0]                    
__________________________________________________________________________________________________
encoder (Encoder)               (None, 256, 1280)    1322154496  tied_embedding_softmax[0][0]     
==================================================================================================
Total params: 1,637,964,550
Trainable params: 1,637,964,550
Non-trainable params: 0
__________________________________________________________________________________________________
None
WARNING:tensorflow:You are creating an Estimator from a Keras model manually subclassed from `Model`, that was already called on some inputs (and thus already had weights). We are currently unable to preserve the model's state (its weights) as part of the estimator in this case. Be warned that the estimator has been created using a freshly initialized version of your model.
Note that this doesn't affect the state of the model instance you passed as `keras_model` argument.
Traceback (most recent call last):
  File "generation.py", line 143, in <module>
    estimator_model = tf.keras.estimator.model_to_estimator(keras_model=model, config=run_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/estimator/__init__.py", line 73, in model_to_estimator
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py", line 462, in model_to_estimator
    estimator = tf.contrib.tpu.TPUEstimator(keras_model_fn, use_tpu=True, train_batch_size=512, eval_batch_size=32,
NameError: global name 'tf' is not defined
```

I got the same error running on a TPU instance of colab. This was run on GPU. What am I doing wrong? I got the same error using the tensorflow/tensorflow:1.14 image as the base too.

**Comment by keskarnitish** [comment]
Seems like there was a weird spacing issue in `estimator.patch`, can you try again with the latest version?

**Comment by pradeepthiyyagura** [comment]
I ran into a similar issue and fixed it by finding the exact location of the keras.py and manually adding
import tensorflow as tf

$sudo find / -name "keras.py"
/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/keras.py
This will give you several options if you have python 3 and 2.7 both installed. Find the file that corresponds to your environment and the correct python version. Then add the import statement at the top and any other code that is not updated after the patch (estimator.patch)

**Comment by calculusoflambdas** [comment]
Thanks - the fix to the patch did the trick, all working now. Awesome work.
