### ISSUE TITLE
Issue with setting temperature

### ISSUE THREAD

**Issue by calculusoflambdas** [salesforce/ctrl#16]
I was getting an error when setting the temperature for the generation script. I think this line:
`            chosen_idx = int(tf.random.categorical(np.expand_dims(prompt_logits[0][_token][pruned_list],0), num_samples=1).numpy())`

Should be
`            chosen_idx = int(tf.random.categorical(np.expand_dims(prompt_logits[_token][pruned_list],0), num_samples=1).numpy())
`
At least that seems to do what I expect. So when I torture the model with problems like this:
```tokens_to_disallow = []
          if token > 0:
            prev=idx2word[tokens_generated[0][token]]
            if not prev.endswith('@@'):
              for _ in range(len(pruned_list)):
                  if not idx2word[pruned_list[_]].lower().startswith('r'):
                    if not idx2word[pruned_list[_]].lower().startswith('t'):
                      if not idx2word[pruned_list[_]].lower().startswith('b'): 
                        tokens_to_disallow.append(_)
              #if 'http' in idx2word[pruned_list[_]]:
              #    tokens_to_disallow.append(_)
          pruned_list = np.delete(pruned_list, tokens_to_disallow)
``` 
it seems to provide some entertaining results with some diversity.

**Comment by calculusoflambdas** [comment]
I think this is needed too for nucleus?
`           pruned_list=pruned_list[:nucleus]  
 `

**Comment by nickwalton** [comment]
I also got this same error.

**Comment by keskarnitish** [comment]
You're absolutely right. Thanks! This was a bug for topk/nucleus sampling (doesn't impact greedy sampling used in repo/paper). I've fixed it in https://github.com/salesforce/ctrl/commit/7b77fdefeced5322dc83f62c746a019655457a3d
