### ISSUE TITLE
Getting UnicodeEncodeErrors

### ISSUE THREAD

**Issue by julienmarie** [salesforce/ctrl#17]
I'm getting these errors in the middle of generation. Any clue why?

Traceback (most recent call last):
  File "generation.py", line 275, in <module>
    print(tokens_generated_so_far)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 289: ordinal not in range(128)

**Comment by keskarnitish** [comment]
Seems to be a system-level Python encoding thing. Can you try `export PYTHONIOENCODING=utf-8` in your terminal before you run the script? That should fix it. Reopen if it doesn't.
