### ISSUE TITLE
How to train/create control codes?

### ISSUE THREAD

**Issue by nullphantom** [salesforce/ctrl#19]
Hi. I am thinking about to train my own control codes. How it is possible?

**Comment by GrahamboJangles** [comment]
The FAQ answers this:

Q: Will you be releasing the training code and data?
A: We plan to release the training code soon. We will not be releasing the training data, but we will release tips and scripts related to data collection.

**Comment by keskarnitish** [comment]
Closing this since it's a duplicate of https://github.com/salesforce/ctrl/issues/8

I'll be adding some discussions there.
