### ISSUE TITLE
pytorch generation error

### ISSUE THREAD

**Issue by loopdigga96** [salesforce/ctrl#27]
Hello, i tried to run generation using pytorch
```
python pytorch_generation.py --model_path ./seqlen256_v1.ckpt/model.ckpt-413000.data-00000-of-00001 --print_once 
```

And get an exception while converting tensorflow model to pytorch:
```
Could not find PyTorch checkpoint
Converting weights and will store the PyTorch checkpoint as  59fb4c9fc12d31d104fd09b35e167d69
Read 200000 codes from the codes file.
2019-09-25 12:29:42.180793: W tensorflow/core/framework/allocator.cc:107] Allocation of 1262254080 exceeds 10% of system memory.
  2%|▏         | 1/48 [00:00<00:05,  8.24it/s]
Traceback (most recent call last):
  File "/home/vlad/Documents/coding/experiments/ctrl/pytorch_generation.py", line 128, in <module>
    current_layer.layernorm1.bias = str2parameter(layer_variables[0])
IndexError: list index out of range

Process finished with exit code 1
```

My environment:
- python 3.6.8
- torch 1.2.0
- tensorflow==1.14.0
- tensorflow-estimator==1.14.0

Also i found an error in 88 line in pytorch_generation.py. You should first encode string to get it hash

```
pytorch_model_hash = hashlib.md5(args.model_path.encode('utf-8')).hexdigest()
```

And I also have a question: Did you test your solution on python3?

**Comment by keskarnitish** [comment]
Should be fixed in https://github.com/salesforce/ctrl/commit/c5bf600133d15cd2bab44d184369e61fdf66d38b

Along with the encoding issue, the Python3 `filter` function was behaving differently to the Python2 one. 

Please reopen if problem persists.

**Comment by loopdigga96** [comment]
@keskarnitish ok i will alter those lines and try again, thank you
