### ISSUE TITLE
Fine-Tuning the Model on Custom Dataset

### ISSUE THREAD

**Issue by htw2012** [salesforce/ctrl#31]
Hello, 

I have a question about fine-tuning the model on custom data.

Is is ok to change the `seq len` in model to fine-tune the `seqlen256_v1.ckpt/` model on custom data?

**Comment by keskarnitish** [comment]
I haven't tried this myself but if the sequence length you chose is less than `256`, I can't think of any reason why it shouldn't work. I can try it out later but if you investigate this before, I'd love to know what you find.
