### ISSUE TITLE
Can a conditional  control code  be multiple tags or  multiple keywords？

### ISSUE THREAD

**Issue by xurongqiang** [salesforce/ctrl#33]
A conditional  control code  in control_codes.txt may be  a class or tag, can  a conditional  control code  be multiple keywords or  multiple entities  and how can I do it ?

**Comment by keskarnitish** [comment]
The way it's trained, the current checkpoints don't support that. However, there is nothing preventing one from fine-tuning (or re-training) CTRL to do that. I'm fairly sure that the model will learn to pick it up.

**Comment by leejason** [comment]
> The way it's trained, the current checkpoints don't support that. However, there is nothing preventing one from fine-tuning (or re-training) CTRL to do that. I'm fairly sure that the model will learn to pick it up.

Does it mean one training record for each tag of the multiple tags? Say, if my average number of multiple tags is 10, the data size for fine-tuning will become 10x of the original? Is this understanding correct? If correct, I plan to give it a try & thank you for your advice.
