### ISSUE TITLE
How to add new control code into vocabulary?

### ISSUE THREAD

**Issue by leejason** [salesforce/ctrl#37]
Is it possible or is there any code for adding new control code into the vocabulary file? 

```
parser.add_argument('--control_code', type=str, required=True,
                                        help='control code to use for this file. must be in the vocabulary, else it will error out.')
```

**Comment by keskarnitish** [comment]
You can't add a control code that isn't in the vocabulary. Typically, exact specification of the token is not needed, a synonym (or really, any unused code) should work. What did you have in mind?

**Comment by leejason** [comment]
[Patent classification codes](https://www.researchgate.net/publication/318873799/figure/tbl1/AS:631674584969269@1527614365448/Top-ten-international-patent-classification-IPC-codes-of-patents-related-to-smart-LED_W640.jpg) which may have 600+ codes. Assuming that such codes are not in vocabulary, would CTRL model work?

**Comment by keskarnitish** [comment]
No, they certainly need to be in the vocabulary at the moment. But, maybe what can work is that you can just start using `word2idx[0], word2idx[1], ..., word2idx[600]` as the control codes? It's convenient for the word used for the control code to have some relevance to the domain but that's not important to the model.

**Comment by leejason** [comment]
Interesting ideas & thanks. Let me try later.
