### ISSUE TITLE
Sampling settings used in the paper

### ISSUE THREAD

**Issue by bkkaggle** [salesforce/ctrl#52]
Hi,

I wanted to ask what sampling settings (temperature, top-k, top-p) were used when generating the text samples in the paper and whether the samples were randomly chosen or were they the best of x tries?

Thanks

**Comment by keskarnitish** [comment]
We used greedy sampling (temperature of `0`) with penalty of `1.2`. These are the defaults for the `generation.py` code. There is no randomness in the code so the results should be deterministically the same (proviso CUDA/GPU versioning randomness).

**Comment by hoangcuong2011** [comment]
Hi @keskarnitish,

the formula for decoding is propotional to exp(logit /(T · I(i ∈ g))). If T = 0 I supposed the factor I(.) (1.2 or 1) should be useless then? Thx.
