### ISSUE TITLE
Custom model conversion to Hugging Face

### ISSUE THREAD

**Issue by orenmelamud** [salesforce/ctrl#57]
Thank you for adding this!
A couple of small issues I encountered when following the instructions:
1. The script requires the transformers package to be installed
2. I had to rename my huggingface checkpoint to pytorch_model.bin and under --model_name_or_path put the directory containing that checkpoint.

**Comment by keskarnitish** [comment]
I'll add to the README that you need `transformers` installed. Thanks!
