### ISSUE TITLE
'tensorflow._api.v1.keras.layers' has no attribute 'LayerNormalization'

### ISSUE THREAD

**Issue by manueltonneau** [salesforce/ctrl#62]
Thanks for the great contribution. 
I'm following the instructions to fine-tune CTRL on the Moby-Dick dataset and faced this error. Any idea why this could happen? Thanks a lot in advance!

More details on the error here:
Traceback (most recent call last):
  File "training.py", line 116, in <module>
    transformed = transformer.Encoder()(embedded, training=False)
  File "../transformer.py", line 116, in __init__
    setattr(self, "layer%i" % i, EncoderLayer(d_model_size, num_heads, dff, rate))
  File "../transformer.py", line 83, in __init__
    self.layernorm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
AttributeError: module 'tensorflow._api.v1.keras.layers' has no attribute 'LayerNormalization'

**Comment by keskarnitish** [comment]
Can you verify that you're using `pip install tensorflow[-gpu]==1.14` ?

**Comment by manueltonneau** [comment]
This solved the problem, thanks!
