### ISSUE TITLE
Using ctrl for summarization

### ISSUE THREAD

**Issue by Hellisotherpeople** [salesforce/ctrl#64]
I can get a abstractive summary using GPT-2 by taking a prompt, appending "TL;DR" to the end, and letting it generate. 

Does CTRL have a better method for this based on control codes? I saw nothing obvious about it in the paper.

**Comment by keskarnitish** [comment]
IIRC, you should use the `News` CTRL code and TL;DR as the triggering token.

**Comment by shamoons** [comment]
Can you give an example of what that prompt would look like?
