### ISSUE TITLE
Download Model Problem

### ISSUE THREAD

**Issue by dpyneo** [salesforce/ctrl#7]
Hello, gsutil is installed, but it can't be downloaded for some reasons. Could you provide a download like "https://drive.google.com/uc?Id=19xQK2onIy-3S5W5K-XIh85pAg_RNvBVf&export=download"? Thank you very much.

**Comment by keskarnitish** [comment]
Sure, I'll look into doing this. 

In the meantime, does this help: https://twitter.com/gwern/status/1171869124613591040?s=20

**Comment by keskarnitish** [comment]
If you navigate to the checkpoint of your choice 
 @ https://console.cloud.google.com/storage/browser/sf-ctrl/ , 
you can download the individual files in the checkpoint using their public links (The link can be found under the public access column). 

For instance, for the `seqlen256_v1.ckpt`, the links are:


```
https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/checkpoint
https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/model.ckpt-413000.data-00000-of-00001
https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/model.ckpt-413000.index
https://storage.googleapis.com/sf-ctrl/seqlen256_v1.ckpt/model.ckpt-413000.meta
```

You can `mkdir -p seqlen256_v1.ckpt` and then `wget` the above files to the same effect as the `gsutil` route. 

Closing for now, reopen as necessary.
