### ISSUE TITLE
control code not recognised

### ISSUE THREAD

**Issue by cainesap** [salesforce/ctrl#78]
Hello,
Thank you for making this great resource available.
I followed the 'fine-tuning' steps described [here](https://github.com/salesforce/ctrl/tree/master/training_utils), and all seemed to go well (no obvious error messages).
But when I try to generate, I see the following warning when I try to use "Moby I" as control code and prompt, as in step 5 example 1:
`You are not starting your generation from a control code so you won't get good results`.
Does this suggest that I haven't done 'converting to TFRecords' (step 3) correctly? If so, would you have any suggestions to investigate further / fix?
thanks, Andrew

**Comment by ThursdaysMan** [comment]
Hi @cainesap,

I'm not part of the team but from what I can understand, having looked into this myself, the **generation.py script imports the control codes from the control_codes.py file in the main folder**. **Running the training.py script trains the model but does not update the control_codes.py file.** 

Having looked through the generation.py code the only part of the control_codes.py dictionary that seems to be used are the keys, and not the id's, so you could manually place the keywords in with a random or edit the training.py script to update a copy in the training_utils folder. **To clarify**, having run the script a number of times with custom prompts and not updating control codes, **it isn't necessary to update the list for the newly trained keywords to work**.

**Someone correct me if they find the dictionary ids doing something in the code**, but I've checked the entire codebase and can't find the ids being used anywhere. 

Hope that helps.

TM

**Comment by cainesap** [comment]
Hi @ThursdaysMan thank you so much for commenting on my issue, I really appreciate this. So yes you are right, if I add the new code to 'control_codes.py' with a dummy value, then I don't get that error message during generation. Fantastic, thanks :) I'll close this issue, and think it'd be helpful if this instruction could be added to the training_utils readme, if it's the correct thing to do @keskarnitish ?
